import './global.css'
import Header from '../components/header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className=''><Header/></header>
        <main>{children}</main>
        <footer className='text-gray-400 text-center text-xs py-5'>Copyright &#64; {new Date().getFullYear()} All right reserved</footer>
        </body>
    </html>
  )
}
